# Generated by Django 6.0.3 on 2026-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=20, unique=True, verbose_name="E-mail"),
                ),
                ("fio", models.CharField(max_length=150, verbose_name="Ф.И.О.")),
                ("comment", models.TextField(verbose_name="Комментарий")),
            ],
            options={
                "ordering": ["email"],
            },
        ),
    ]
